reviews:
  # 자동 리뷰를 허용할 브랜치 목록

  review_status: true

  base_branches:
    - main
    - develop
    - feat/*
    - refactor/*
    - bug/*

  # 리뷰 룰 설정 (원하는 대로 조정 가능)
  rules:
    - code-quality
    - performance
    - security
    - readability
    - best-practices

  # 리뷰 설명 스타일
  comments:
    style: concise # 또는: detailed

  # 각 리뷰에 AI 요약 포함 여부
  summary: true

  # 한글로 리뷰하기 위한 설정
  language: ko

  # 리뷰 메시지 언어 설정
  messages:
    language: ko

  # 리뷰 설명 언어 설정
  descriptions:
    language: ko
