import type { Metadata } from "next";
import { gangwonEdu, pretendard } from "@/public/fonts/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${gangwonEdu.variable} ${pretendard.variable}`}>
        <main
          style={{
            position: "fixed",
            display: "flex",
            zIndex: 10,
            flexDirection: "column",
            alignContent: "center",
            width: "100%",
            maxWidth: "768px",
            height: "100svh",
            // maxHeight: "100svh",
            border: `1px solid #d9d9d9`,
            overflowX: "hidden",
            overflowY: "auto",
            scrollbarWidth: "none",
            msOverflowStyle: "none",
          }}
        >
          {children}
        </main>
      </body>
    </html>
  );
}
